name: ğŸš€ Despliegue Web

on:
  push:
    branches: [main]
  workflow_dispatch:

# Permisos necesarios para el despliegue
permissions:
  contents: read
  pages: write
  id-token: write

# Control de concurrencia
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ› ï¸ Obtener cÃ³digo
        uses: actions/checkout@v4
      
      - name: ğŸ” Verificar contenido de la carpeta web
        run: |
          echo "Contenido de la carpeta web:"
          ls -la web/
      
      - name: ï¿½ Crear archivo .nojekyll
        run: touch web/.nojekyll
      
      - name: ï¿½ğŸ”„ Configurar Pages
        uses: actions/configure-pages@v4
      
      - name: ğŸ“¦ Subir archivos de la carpeta web
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'web/'  # Asegura que se suba el contenido de la carpeta

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ğŸš€ Desplegar
        id: deployment
        uses: actions/deploy-pages@v4